version: '3.5'

networks:

  network:
    name: lemp_network
    driver: bridge

services:

  debian:
    image: yareg/lemp
    container_name: lemp_debian
    ports:
      - 9001:80
    volumes:
      # Re-use local composer cache via host-volume
      #- ~/.composer-docker/cache:/root/.composer/cache:delegated
      # Mount composer auth file
      #- ./composer-auth.json:/root/.composer/auth.json:ro
      # Mount source-code for development
      - ./:/opt/app
    networks:
      - network
    #restart: always
